FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

FROM base AS development

# This EXPOSE is entirely for documentation purposes. This doesn't actually force the PORT to be 3000.
EXPOSE 3000

CMD ["npm", "run", "dev"]
